#!/bin/sh
# 23a — Install Fish shell + fetch config from unix flake
# One command: installs fish, sets as default, deploys all config files
set -eu

SUDO="sudo"
[ "$(id -u)" = "0" ] && SUDO=""
UNIX_REPO="${HOME}/git/unix"
FISH_DIR="${HOME}/.config/fish"
STARSHIP_DIR="${HOME}/.config"

echo "=== Fish Shell Setup ==="

# ── Step 1: Install Fish ─────────────────────────────────────────
if command -v fish >/dev/null 2>&1; then
    echo "[OK] Fish already installed: $(fish --version 2>/dev/null)"
else
    echo "[+] Installing Fish shell..."
    if command -v dnf >/dev/null 2>&1; then
        $SUDO dnf install -y fish
    elif command -v apt-get >/dev/null 2>&1; then
        $SUDO apt-get update -qq && $SUDO apt-get install -y -qq fish
    elif command -v pacman >/dev/null 2>&1; then
        $SUDO pacman -S --noconfirm fish
    elif command -v apk >/dev/null 2>&1; then
        $SUDO apk add fish
    elif command -v nix-env >/dev/null 2>&1; then
        nix-env -iA nixpkgs.fish
    else
        echo "[!] No supported package manager — install fish manually"
    fi
fi

# ── Step 2: Set as default shell ─────────────────────────────────
if command -v fish >/dev/null 2>&1; then
    FISH_PATH=$(command -v fish)
    if ! grep -q "$FISH_PATH" /etc/shells 2>/dev/null; then
        echo "$FISH_PATH" | $SUDO tee -a /etc/shells >/dev/null 2>&1 && echo "[+] Added $FISH_PATH to /etc/shells" || echo "[!] /etc/shells read-only (NixOS) — fish already usable"
    fi
    CURRENT_SHELL=$(getent passwd "$(whoami)" 2>/dev/null | cut -d: -f7 || echo "")
    if [ "$CURRENT_SHELL" != "$FISH_PATH" ]; then
        $SUDO chsh -s "$FISH_PATH" "$(whoami)" 2>/dev/null && echo "[+] Default shell set to Fish" || echo "[!] chsh skipped (NixOS manages shells declaratively)"
    else
        echo "[OK] Fish is already the default shell"
    fi
fi

# ── Step 3: Clone unix repo if needed ────────────────────────────
if [ ! -d "$UNIX_REPO" ]; then
    echo "[+] Cloning unix repo..."
    mkdir -p "$(dirname "$UNIX_REPO")"
    git clone --depth 1 https://github.com/diegonmarcos/unix.git "$UNIX_REPO"
else
    echo "[OK] Unix repo exists at $UNIX_REPO"
fi

# ── Step 4: Deploy fish config ───────────────────────────────────
mkdir -p "$FISH_DIR/conf.d" "$FISH_DIR/functions"
if [ -L "$FISH_DIR/config.fish" ] || ! touch "$FISH_DIR/config.fish" 2>/dev/null; then
    echo "[OK] config.fish managed by home-manager — skipping write"
    echo "[OK] starship.toml managed by home-manager — skipping write"
    echo "=== Done (HM-managed system) ==="
    exit 0
fi
echo "[+] Writing config.fish..."
cat > "$FISH_DIR/config.fish" << 'FISHCONF'
# Generated by dtk.sh 23a (source: unix/ba_flakes_desktop/src/modules/programs/shells/fish.nix)
if status is-interactive
    # Modern CLI
    alias ls="eza --color=auto --icons 2>/dev/null || command ls --color=auto"
    alias ll="eza -alF --icons 2>/dev/null || command ls -alF"
    alias la="eza -A --icons 2>/dev/null || command ls -A"
    alias l="eza -CF --icons 2>/dev/null || command ls -CF"
    alias lt="eza --tree --level=2 --icons 2>/dev/null || tree -L 2"
    alias cat="bat --paging=never 2>/dev/null || command cat"
    alias grep="rg 2>/dev/null || command grep --color=auto"
    alias find="fd 2>/dev/null || command find"
    alias ..="cd .."; alias ...="cd ../.."; alias ....="cd ../../.."
    alias rm="rm -i"; alias cp="cp -i"; alias mv="mv -i"
    alias df="duf 2>/dev/null || command df -h"
    alias du="ncdu 2>/dev/null || command du -sh"
    alias free="free -h"; alias ports="ss -tulanp"; alias myip="curl -s ifconfig.me"
    alias py="python3"; alias python="python3"; alias pip="pip3"
    alias c="clear"; alias cls="clear"; alias h="history"
    alias reload="source ~/.config/fish/config.fish"
    alias dtk="bash ~/git/tools/dtk.sh"
    # Git
    abbr -a gs "git status -sb"
    abbr -a ga "git add"; abbr -a gaa "git add --all"
    abbr -a gc "git commit"; abbr -a gcm "git commit -m"
    abbr -a gp "git push"; abbr -a gpl "git pull"
    abbr -a gl "git log --oneline --graph --decorate -20"
    abbr -a gd "git diff"; abbr -a gco "git checkout"; abbr -a gcl "git clone"
    # Docker
    abbr -a dps "docker ps"; abbr -a dpsa "docker ps -a"
    abbr -a dcu "docker compose up"; abbr -a dcd "docker compose down"
    abbr -a dcl "docker compose logs -f"
    # PATH
    fish_add_path -m ~/.cargo/bin ~/.npm-global/bin ~/go/bin ~/.local/bin ~/.nix-profile/bin
    # Prompts
    if command -q starship; starship init fish | source; end
    if command -q zoxide; zoxide init fish | source; end
end
FISHCONF

# ── Step 5: Deploy starship config ───────────────────────────────
echo "[+] Writing starship.toml..."
mkdir -p "$STARSHIP_DIR"
cat > "$STARSHIP_DIR/starship.toml" << 'STAR'
format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"
[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
[directory]
truncation_length = 3
[git_branch]
format = "[$branch]($style) "
[cmd_duration]
min_time = 2000
STAR

# ── Step 6: Copy fish greeting from flake ─────────────────────────
GREETING_SRC="$UNIX_REPO/ba_flakes_desktop/src/modules/programs/shells/fish.nix"
if [ -f "$GREETING_SRC" ]; then
    echo "[OK] Fish flake source: $GREETING_SRC"
else
    echo "[!] Flake source not found — config.fish still works with defaults"
fi

echo "=== Done ==="
echo "[OK] config.fish    → $FISH_DIR/config.fish"
echo "[OK] starship.toml  → $STARSHIP_DIR/starship.toml"
echo ""
echo "Run: source ~/.config/fish/config.fish"
