#!/bin/sh
# Fetch fish config from unix flake (ba_flakes_desktop) and install locally
# Source: unix/ba_flakes_desktop/src/modules/programs/shells/
set -eu

UNIX_REPO="${HOME:-/home/diego}/git/unix"
FISH_SRC="$UNIX_REPO/ba_flakes_desktop/src/modules/programs/shells"
FISH_DIR="${HOME:-/home/diego}/.config/fish"
STARSHIP_DIR="${HOME:-/home/diego}/.config"

echo "=== Fish Config Installer ==="
echo "Source: $FISH_SRC"
echo "Target: $FISH_DIR"

# Clone unix repo if not present
if [ ! -d "$UNIX_REPO" ]; then
    echo "Cloning unix repo..."
    mkdir -p "$(dirname "$UNIX_REPO")"
    git clone --depth 1 https://github.com/diegonmarcos/unix.git "$UNIX_REPO"
fi

# Ensure fish config dir exists
mkdir -p "$FISH_DIR/conf.d" "$FISH_DIR/functions"

# Extract aliases + abbreviations from fish.nix and generate config.fish
echo "Generating config.fish from flake..."
cat > "$FISH_DIR/config.fish" << 'FISHCONF'
# Generated by dtk.sh fish-config (from unix/ba_flakes_desktop/src/modules/programs/shells/fish.nix)
# Source of truth: ~/git/unix/ba_flakes_desktop/src/modules/programs/shells/fish.nix
if status is-interactive
    # Modern CLI aliases
    alias ls="eza --color=auto --icons 2>/dev/null || command ls --color=auto"
    alias ll="eza -alF --icons 2>/dev/null || command ls -alF"
    alias la="eza -A --icons 2>/dev/null || command ls -A"
    alias l="eza -CF --icons 2>/dev/null || command ls -CF"
    alias lt="eza --tree --level=2 --icons 2>/dev/null || tree -L 2"
    alias cat="bat --paging=never 2>/dev/null || command cat"
    alias grep="rg 2>/dev/null || command grep --color=auto"
    alias find="fd 2>/dev/null || command find"

    # Navigation
    alias ..="cd .."; alias ...="cd ../.."; alias ....="cd ../../.."

    # Safety
    alias rm="rm -i"; alias cp="cp -i"; alias mv="mv -i"

    # System
    alias df="duf 2>/dev/null || command df -h"
    alias du="ncdu 2>/dev/null || command du -sh"
    alias free="free -h"
    alias ports="ss -tulanp"
    alias myip="curl -s ifconfig.me"

    # Python
    alias py="python3"; alias python="python3"; alias pip="pip3"

    # Misc
    alias c="clear"; alias cls="clear"; alias h="history"
    alias reload="source ~/.config/fish/config.fish"

    # Custom tools
    alias dtk="bash ~/git/tools/dtk.sh"

    # Git abbreviations
    abbr -a gs "git status -sb"
    abbr -a ga "git add"; abbr -a gaa "git add --all"
    abbr -a gc "git commit"; abbr -a gcm "git commit -m"
    abbr -a gp "git push"; abbr -a gpl "git pull"
    abbr -a gl "git log --oneline --graph --decorate -20"
    abbr -a gd "git diff"; abbr -a gco "git checkout"
    abbr -a gcl "git clone"

    # Docker abbreviations
    abbr -a dps "docker ps"; abbr -a dpsa "docker ps -a"
    abbr -a dcu "docker compose up"; abbr -a dcd "docker compose down"
    abbr -a dcl "docker compose logs -f"

    # PATH
    fish_add_path -m ~/.cargo/bin ~/.npm-global/bin ~/go/bin ~/.local/bin ~/.nix-profile/bin

    # Starship prompt
    if command -q starship; starship init fish | source; end
    # Zoxide
    if command -q zoxide; zoxide init fish | source; end
end
FISHCONF

echo "config.fish written"

# Install starship config if starship available
if command -v starship >/dev/null 2>&1; then
    if [ ! -f "$STARSHIP_DIR/starship.toml" ]; then
        cat > "$STARSHIP_DIR/starship.toml" << 'STAR'
format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"
[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
[directory]
truncation_length = 3
[git_branch]
format = "[$branch]($style) "
[cmd_duration]
min_time = 2000
STAR
        echo "starship.toml written"
    else
        echo "starship.toml already exists — skipped"
    fi
fi

echo "=== Done ==="
echo "Run: source ~/.config/fish/config.fish"
