#!/bin/sh
# 23a — Install Fish + deps + fetch ALL config files from unix repo (raw GitHub)
set -eu

SUDO="sudo"
[ "$(id -u)" = "0" ] && SUDO=""
FISH_DIR="${HOME}/.config/fish"
STARSHIP_DIR="${HOME}/.config"

# Source of truth: unix repo fish asset files
RAW="https://raw.githubusercontent.com/diegonmarcos/unix/main/ba_flakes_desktop/src/modules/programs/shells/fish"

echo "=== Fish Shell Setup ==="

# ── Step 1: Install Fish ─────────────────────────────────────────
if command -v fish >/dev/null 2>&1; then
    echo "[OK] Fish installed: $(fish --version 2>/dev/null)"
else
    echo "[+] Installing Fish..."
    if command -v dnf >/dev/null 2>&1; then $SUDO dnf install -y fish
    elif command -v apt-get >/dev/null 2>&1; then $SUDO apt-get update -qq && $SUDO apt-get install -y -qq fish
    elif command -v pacman >/dev/null 2>&1; then $SUDO pacman -S --noconfirm fish
    elif command -v apk >/dev/null 2>&1; then $SUDO apk add fish
    elif command -v nix-env >/dev/null 2>&1; then nix-env -iA nixpkgs.fish
    else echo "[!] No package manager — install fish manually"; fi
fi

# ── Step 2: Install tool dependencies ────────────────────────────
# These are the tools that aliases/functions depend on
echo "[+] Installing shell tool dependencies..."

_install_pkg() {
    _pkg="$1"
    _apt_name="${2:-$1}"
    if command -v "$_pkg" >/dev/null 2>&1; then
        echo "[OK] $_pkg"
        return 0
    fi
    if command -v apt-get >/dev/null 2>&1; then
        $SUDO apt-get install -y -qq "$_apt_name" 2>/dev/null \
            && echo "[OK] $_pkg (installed)" \
            || echo "[!] $_pkg not available via apt"
    elif command -v dnf >/dev/null 2>&1; then
        $SUDO dnf install -y "$_apt_name" 2>/dev/null \
            && echo "[OK] $_pkg (installed)" \
            || echo "[!] $_pkg not available via dnf"
    elif command -v pacman >/dev/null 2>&1; then
        $SUDO pacman -S --noconfirm "$_apt_name" 2>/dev/null \
            && echo "[OK] $_pkg (installed)" \
            || echo "[!] $_pkg not available via pacman"
    elif command -v apk >/dev/null 2>&1; then
        $SUDO apk add "$_apt_name" 2>/dev/null \
            && echo "[OK] $_pkg (installed)" \
            || echo "[!] $_pkg not available via apk"
    else
        echo "[!] $_pkg — no package manager to install"
    fi
}

# Core tools (aliases depend on these)
_install_pkg eza eza
_install_pkg bat bat
_install_pkg rg ripgrep
_install_pkg fd fd-find
_install_pkg duf duf
_install_pkg ncdu ncdu
_install_pkg jq jq
_install_pkg curl curl
_install_pkg git git
_install_pkg starship starship
_install_pkg zoxide zoxide
_install_pkg fzf fzf
_install_pkg tmux tmux

# ── Step 3: Set as default shell ─────────────────────────────────
if command -v fish >/dev/null 2>&1; then
    FISH_PATH=$(command -v fish)
    grep -q "$FISH_PATH" /etc/shells 2>/dev/null || echo "$FISH_PATH" | $SUDO tee -a /etc/shells >/dev/null 2>&1 || true
    CURRENT_SHELL=$(getent passwd "$(whoami)" 2>/dev/null | cut -d: -f7 || echo "")
    [ "$CURRENT_SHELL" != "$FISH_PATH" ] && $SUDO chsh -s "$FISH_PATH" "$(whoami)" 2>/dev/null && echo "[+] Default shell: fish" || true
fi

# ── Step 4: Skip if HM-managed ───────────────────────────────────
if [ -L "$FISH_DIR/config.fish" ] || ! mkdir -p "$FISH_DIR" 2>/dev/null || ! touch "$FISH_DIR/.test" 2>/dev/null; then
    echo "[OK] Fish config managed by home-manager — skipping"
    exit 0
fi
rm -f "$FISH_DIR/.test"

# ── Step 5: Generate config.fish with fallback aliases ───────────
# HM aliases are hard (assume tool exists). For non-HM we generate
# aliases with graceful fallback so they work even if a tool is missing.
mkdir -p "$FISH_DIR/functions" "$FISH_DIR/conf.d" "$FISH_DIR/completions"

echo "[+] Generating config.fish with fallback aliases..."
cat > "$FISH_DIR/config.fish" << 'FISHCONF'
# Generated by dtk.sh 23a — non-HM config with fallback aliases
if status is-interactive
    # Modern CLI with fallbacks
    if command -q eza
        alias ls="eza --color=auto --icons"
        alias ll="eza -alF --icons"
        alias la="eza -A --icons"
        alias l="eza -CF --icons"
        alias lh="eza -lh --icons"
        alias lt="eza --tree --level=2 --icons"
    else
        alias ls="command ls --color=auto"
        alias ll="command ls -alF --color=auto"
        alias la="command ls -A --color=auto"
        alias l="command ls -CF --color=auto"
        alias lh="command ls -lh --color=auto"
        alias lt="tree -L 2 2>/dev/null; or command ls -R"
    end
    if command -q bat;    alias cat="bat --paging=never"; end
    if command -q rg;     alias grep="rg"; end
    if command -q fd;     alias find="fd"; end
    if command -q duf;    alias df="duf";  else; alias df="command df -h"; end
    if command -q ncdu;   alias du="ncdu"; else; alias du="command du -sh"; end

    # Navigation
    alias ..="cd .."; alias ...="cd ../.."; alias ....="cd ../../.."

    # Safety
    alias rm="rm -i"; alias cp="cp -i"; alias mv="mv -i"

    # Python
    alias py="python3"; alias python="python3"; alias pip="pip3"

    # System
    alias free="free -h"
    alias ports="ss -tulanp"
    alias myip="curl -s ifconfig.me"

    # Misc
    alias c="clear"; alias cls="clear"; alias h="history"
    alias path="echo \$PATH | tr ':' '\\n'"
    alias reload="source ~/.config/fish/config.fish"

    # Custom tools
    alias dtk="bash ~/git/tools/dtk.sh"

    # Git abbreviations
    abbr -a gs "git status -sb"; abbr -a ga "git add"; abbr -a gaa "git add --all"
    abbr -a gc "git commit"; abbr -a gcm "git commit -m"
    abbr -a gp "git push"; abbr -a gpl "git pull"; abbr -a gcl "git clone"
    abbr -a gl "git log --oneline --graph --decorate -20"
    abbr -a gd "git diff"; abbr -a gco "git checkout"

    # Docker abbreviations
    abbr -a dps "docker ps"; abbr -a dpsa "docker ps -a"
    abbr -a dcu "docker compose up"; abbr -a dcd "docker compose down"

    # PATH
    fish_add_path -m ~/.cargo/bin ~/.npm-global/bin ~/go/bin ~/.local/bin ~/.nix-profile/bin

    # Integrations (only if installed)
    if command -q starship; starship init fish | source; end
    if command -q zoxide;   zoxide init fish | source; end
    if command -q fzf;      fzf --fish | source; end
    if command -q direnv;   direnv hook fish | source; end
end
FISHCONF
echo "[OK] config.fish"

# ── Step 6: Fetch functions from unix repo ───────────────────────
echo "[+] Fetching fish functions from unix repo..."

# HM uses builtins.readFile for the body; non-HM needs full function wrapper
FUNCS_URL="$RAW/functions"
for fn in fish_greeting ai-cli cloud-ai-cli gacp gcam gpsh git_current_branch \
          extract mkcd mkd serve hhelp myhelp localip duh backup cpucap qfind \
          hg fish-e fish-e-stop __fzf_search_commands; do
    _body_tmp=$(mktemp)
    if curl -sfL "$FUNCS_URL/${fn}.fish" -o "$_body_tmp" 2>/dev/null && [ -s "$_body_tmp" ]; then
        {
            echo "function $fn"
            sed 's/^/  /' "$_body_tmp"
            echo "end"
        } > "$FISH_DIR/functions/${fn}.fish"
        echo "[OK] functions/${fn}.fish"
    else
        echo "[!] functions/${fn}.fish not found"
    fi
    rm -f "$_body_tmp"
done

# ── Step 7: Starship config ──────────────────────────────────────
echo "[+] Writing starship.toml..."
mkdir -p "$STARSHIP_DIR"
cat > "$STARSHIP_DIR/starship.toml" << 'STAR'
format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"
[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
[directory]
truncation_length = 3
[git_branch]
format = "[$branch]($style) "
[cmd_duration]
min_time = 2000
STAR
echo "[OK] starship.toml"

echo ""
echo "=== Done ==="
echo "Files deployed:"
echo "  ~/.config/fish/config.fish"
echo "  ~/.config/fish/functions/ ($(ls "$FISH_DIR/functions/" 2>/dev/null | wc -l) files)"
echo "  ~/.config/starship.toml"
echo ""
echo "Run: source ~/.config/fish/config.fish"
